"""Add analysis_runs table

Revision ID: 707e76dba275
Revises: a1b2c3d4e5f6
Create Date: 2026-08-17 10:57:12.828337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '707e76dba275'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('current_agent', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_startup_id'), 'analysis_runs', ['startup_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.add_column('startups', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('startups', sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('startups', 'solution')
    op.drop_column('startups', 'problem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('problem', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('solution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('startups', 'additional_info')
    op.drop_column('startups', 'industry')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_startup_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
