"""Add startups table

Revision ID: 9d8c2a7b6a0f
Revises: bbe4ecd79120
Create Date: 2026-08-14 19:02:10.612018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d8c2a7b6a0f'
down_revision: Union[str, Sequence[str], None] = 'bbe4ecd79120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('solution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('business_model', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('unique_value_proposition', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('competitors', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_user_id'), 'startups', ['user_id'], unique=False)
    op.add_column('users', sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_index(op.f('ix_startups_user_id'), table_name='startups')
    op.drop_table('startups')
    # ### end Alembic commands ###
