"""remove_ai_fields_from_startup

Revision ID: a1b2c3d4e5f6
Revises: 9d8c2a7b6a0f
Create Date: 2026-08-14 19:53:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '9d8c2a7b6a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startups', 'competitors')
    op.drop_column('startups', 'unique_value_proposition')
    op.drop_column('startups', 'business_model')
    op.drop_column('startups', 'stage')
    op.drop_column('startups', 'industry')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(length=50), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('business_model', sqlmodel.sql.sqltypes.AutoString(length=2000), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('unique_value_proposition', sqlmodel.sql.sqltypes.AutoString(length=2000), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('competitors', sqlmodel.sql.sqltypes.AutoString(length=3000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
